### ISSUE TITLE
Define `exp.sdkVersion` in `package.json`

### ISSUE THREAD

**Issue by dchambers** [Charca/reactjs-conf-2016#1]
I was seeing this error with the current version of Exponent (1.7.0):

```
Error: Can't find key exp.sdkVersion in package.json. See https://exponentjs.com/help
```

which I was able to fix by adding this line:

```
"sdkVersion": "4.0.0",
```

to the `exp` section of `package.json`.

**Comment by Charca** [comment]
Just added it. Thanks @dchambers!
